### ISSUE TITLE
只有一个readme吗

### ISSUE THREAD

**Issue by weathon** [ZjzMisaka/iaders#1]

**Comment by weathon** [comment]
只有一个readme吗

**Comment by weathon** [comment]
@ZjzMisaka

**Comment by ZjzMisaka** [comment]
> 只有一个自述吗

还没有去添加内容, 因为我很懒...而且也确实没人看, 不怎么着急. 手上有一个放了网站全部文章的数据表, 准备把每条正文提取到一个单独的文件, 按作者分类贴上GitHub.

**Comment by weathon** [comment]
好，注意保护隐私。我是qq上那个栈堆储存器，最近qq用不了

**Comment by ZjzMisaka** [comment]
> 好，注意保护隐私。我是qq上那个栈堆储存器，最近qq用不了

这件事, 能不能交给你来处理, 因为需要py的知识, 你来好像更合适.

**Comment by ZjzMisaka** [comment]
> 好，注意保护隐私。我是qq上那个栈堆储存器，最近qq用不了

我把表中需要的内容提取到一个csv文件里了, 可以用excel正常打开. 每一行代表一个文章, 有三列分别是标题, 正文, 发布时间. 需要做的是把每行的标题作为文件名, 正文作为文件内容, 正文后附加上时间, 单独提取出来.

**Comment by weathon** [comment]
可以，要建立网站的话可以用layui，解析文档可以在前端进行

**Comment by weathon** [comment]
所以其实不用py（当然，用也可以，但涉及到服务器毕竟容易出现安全问题），你可以建立一个私有repo（现在GitHub可以免费建立了）然后share给我

**Comment by weathon** [comment]
@ZjzMisaka

**Comment by weathon** [comment]
文章内容是纯文本吗？界面做简陋一些可以吗

**Comment by ZjzMisaka** [comment]
> 文章内容是纯文本吗？界面做简陋一些可以吗

我下午给你做一下样例然后发邮件给你, 你就懂了.

**Comment by weathon** [comment]
你知道我邮箱吗？我个人主页应该有写，不要发qq邮箱

**Comment by weathon** [comment]
你看看界面可以用https://www.weathon.top/blog这样的吗

**Comment by weathon** [comment]
https://www.weathon.top/blog

**Comment by weathon** [comment]
@ZjzMisaka 
~顺便一提，你那个服务器我还是用不了，手机电脑又被没收了~

**Comment by ZjzMisaka** [comment]
可以看一下, 我整了两个示例. 
excel表格内的正文列本来就自带html标签的, 所以可以存为.md格式让github识别. 
有一点是, 文件内容还是需要修改一些无法识别的标签, 例如: 

> <a href=""https://www.iaders.com/lywjzx/friends/4963/attachment/cropped-cropped-f9c14d35ed9bfd4d-1-%e5%89%af%e6%9c%ac-1-png/#main"" rel=""attachment wp-att-2522""><img class=""aligncenter size-full wp-image-2522"" src=""https://www.iaders.com/wp-content/uploads/2017/11/cropped-cropped-f9c14d35ed9bfd4d-1-副本-1.png"" alt="""" width=""522"" height=""120"">

> [caption id=""attachment_5196"" align=""aligncenter"" width=""500""]<a href=""https://www.iaders.com/lywjzx/friends/5194/attachment/%e6%9d%8e%e5%85%8b%e5%bc%ba2/#main"" rel=""attachment wp-att-5196""><img class=""size-full wp-image-5196"" src=""https://www.iaders.com/wp-content/uploads/2019/01/李克强2.jpg"" alt=""李克强在国务院第二次廉政工作会议上讲话"" width=""500"" height=""329""></a> 李克强在国务院第二次廉政工作会议上讲话[/caption]

这些是无法识别的. 你可以把iaders作为关键词, 直接去除包含这个词的行. 去除之前可以把里面的图片链接提取出来, 用正确的markdown格式替换在原来的位置.

**Comment by weathon** [comment]
> 这些是无法识别的. 你可以把iaders作为关键词, 直接去除包含这个词的行. 去除之前可以把里面的图片链接提取出来, 用正确的markdown格式替换在原来的位置.
@ZjzMisaka 这段没看懂

**Comment by weathon** [comment]
我最近要崩溃炸了，真的很多烦事。
考试也没考好，又感到孤独，写代码也写不了，和甲方又联系不上，身体也不舒服

**Comment by weathon** [comment]
html的话直接存html啊，为什么要md

**Comment by weathon** [comment]
html用GitHub page

**Comment by weathon** [comment]
我先休息了，晚安

**Comment by ZjzMisaka** [comment]
> > 这些是无法识别的. 你可以把iaders作为关键词, 直接去除包含这个词的行. 去除之前可以把里面的图片链接提取出来, 用正确的markdown格式替换在原来的位置.
> > @ZjzMisaka 这段没看懂

下面是原文档里一段不能识别的图片html代码
`<a href=""https://www.iaders.com/lywjzx/friends/4963/attachment/cropped-cropped-f9c14d35ed9bfd4d-1-%e5%89%af%e6%9c%ac-1-png/#main"" rel=""attachment wp-att-2522""><img class=""aligncenter size-full wp-image-2522"" src=""https://www.iaders.com/wp-content/uploads/2017/11/cropped-cropped-f9c14d35ed9bfd4d-1-副本-1.png"" alt="""" width=""522"" height=""120""></a>`
需要替换成如下样子的markdown格式
`![图片标题](https://www.iaders.com/wp-content/uploads/2017/11/cropped-cropped-f9c14d35ed9bfd4d-1-副本-1.png)`
至于为什么用iaders作关键词, 是因为包含了iaders的行, 几乎都不能被识别. 
至于为什么不能用html格式, 你用脚趾头也应该想得明白啊, 假设一个路人如果来看我的这个网站数据整理,  你觉得是给他看一坨html标签好还是给他看github里自动渲染好排版的.md文件好? 
[科普.md](https://github.com/ZjzMisaka/iaders/blob/master/root/ZjzMisaka/ZjzMisaka-%E5%BC%BA%E5%88%B6%E5%8C%BB%E7%96%97%E7%9B%B8%E5%85%B3%E6%B3%95%E5%BE%8B%E4%B8%8E%E6%A6%82%E5%BF%B5%E7%A7%91%E6%99%AE.md).
[科普.html](https://github.com/ZjzMisaka/iaders/blob/master/root/ZjzMisaka/ZjzMisaka-%E5%BC%BA%E5%88%B6%E5%8C%BB%E7%96%97%E7%9B%B8%E5%85%B3%E6%B3%95%E5%BE%8B%E4%B8%8E%E6%A6%82%E5%BF%B5%E7%A7%91%E6%99%AE.html
)
我又上传了个html文件, 你看看差别.

**Comment by ZjzMisaka** [comment]
> GitHub page

我是要做数据整理, 不是建立站点, 大哥...

**Comment by weathon** [comment]
> >GitHub page

> 我是要做数据整理, 不是建立站点, 大哥...
好吧，我看看怎么弄

**Comment by ZjzMisaka** [comment]
> > > GitHub page
> 
> > 我是要做数据整理, 不是建立站点, 大哥...
> > 好吧，我看看怎么弄

我把最新的csv文件传上来了, 你先看看吧, 
第一列是标题 (格式是 "作者名: 标题"), 第二列是摘要 (似乎只有一行有内容, 所以干脆别管了, 到时候手动处理), 第三列是正文, 第四列是转载时间. 
现在需要把第一列拆分开来, 作者名作为文件夹名存放同一作者的文章, 标题作为.md文件的文件名. 
第二列不管, 到时候把有内容的手动添加到正文前面
第三行正文是.md文件的内容, 需要对无法识别的部分做变动
第四列时间, 添加到正文最后. 
辛苦了, 在这次批量增加之后如果再有新的文章就由我来手动搬运了. 
以前网站招过两个小编, 只干了一个星期活转载了三篇文章就再也不吭声了, 不知道这次在github会不会有那么一点改善, 不知道有生之年会不会看到有人提交分支...

**Comment by weathon** [comment]
我不是提交分支了吗

**Comment by weathon** [comment]
csv文件编码又问题

**Comment by ZjzMisaka** [comment]
> csv文件编码又问题

中文环境我转成ansi了, 我不知道你那应该用什么编码, 你可以转一下试一下utf-8, 文件原本是utf-8编码的.

**Comment by ZjzMisaka** [comment]
> 我不是提交分支了吗

我指的是那种路人贡献一篇新的我没上传过的文章的分支_(:з」∠)_

**Comment by weathon** [comment]
你觉得pdf和md哪个好

**Comment by ZjzMisaka** [comment]
> 你觉得pdf和md哪个好

md. 我上传那些pdf只是因为那些那些论文只有pdf格式而已. 你觉得pdf更好么, 按理说pdf不是不可以.

**Comment by weathon** [comment]
都可以，md加载快一些，pdf便于读者下载

**Comment by weathon** [comment]
还有，我不建议用csv，有时候会乱，因为csv是逗号分隔的

**Comment by ZjzMisaka** [comment]
> 还有，我不建议用csv，有时候会乱，因为csv是逗号分隔的

那你自己决定吧, 但我需要保证在线查看时的可读性, 排版不能太难看.

**Comment by weathon** [comment]
你加我微信吧，151075七三六四四

**Comment by ZjzMisaka** [comment]
> 还有，我不建议用csv，有时候会乱，因为csv是逗号分隔的

py我记得有自带csv模块的, 你直接调用里边函数就可以提取了. 因为csv本身就是用来以文本形式存储表格数据的.

**Comment by weathon** [comment]
csv是纯文本文件，手动处理就行
我的疑问是，csv是逗号分隔，万一内容也有逗号似乎会被转译

**Comment by weathon** [comment]
由于这个issues的部分内容包含了我的个人资料，我删掉了一部分，但是你的回复似乎删不了
@ZjzMisaka
